In [1]:
import torch

def run_pytorch_cuda_test():
    """
    執行 PyTorch CUDA 功能的完整測試。
    """
    print(f"PyTorch 版本: {torch.__version__}")
    print("-" * 40)

    # 1. 檢查 CUDA 是否可用
    is_available = torch.cuda.is_available()
    print(f"CUDA 是否可用: {is_available}")

    if not is_available:
        print("警告: PyTorch 無法偵測到 CUDA。請檢查您的 PyTorch 安裝版本是否支援 GPU，")
        print("以及 NVIDIA 驅動程式是否已正確安裝。")
        return

    print("-" * 40)

    # 2. 獲取 GPU 資訊
    try:
        device_count = torch.cuda.device_count()
        print(f"偵測到的 GPU 數量: {device_count}")

        current_device_id = torch.cuda.current_device()
        print(f"目前使用的 GPU ID: {current_device_id}")

        current_device_name = torch.cuda.get_device_name(current_device_id)
        print(f"目前 GPU 名稱: {current_device_name}")

        # PyTorch 編譯時所用的 CUDA 版本
        pytorch_cuda_version = torch.version.cuda
        print(f"PyTorch 編譯所用的 CUDA 版本: {pytorch_cuda_version}")
        print("-" * 40)

        # 3. 執行基本的 GPU 運算
        print("執行一個簡單的張量運算來驗證 CUDA 核心...")

        # 創建一個張量並將其移動到 GPU
        # 'cuda' 或 'cuda:0' 都可以代表第一張 GPU
        device = torch.device("cuda")
        tensor_cpu = torch.randn(3, 4)
        tensor_gpu = tensor_cpu.to(device)

        print(f"原始 CPU 張量:\n {tensor_cpu}")
        print(f"移動到 GPU 後的張量:\n {tensor_gpu}")
        print(f"張量所在的設備: {tensor_gpu.device}")

        # 在 GPU 上執行運算
        result_gpu = tensor_gpu * 2 + 1
        print(f"\n在 GPU 上運算的結果:\n {result_gpu}")

        # 將結果移回 CPU (如果需要)
        result_cpu = result_gpu.cpu()
        print(f"\n將結果移回 CPU:\n {result_cpu}")
        print(f"運算結果所在的設備: {result_cpu.device}")

        print("\n測試成功！PyTorch 已正確在您的 GPU 上執行運算。")

    except Exception as e:
        print(f"\n測試過程中發生錯誤: {e}")
        print("請檢查您的環境配置。")

if __name__ == "__main__":
    run_pytorch_cuda_test()

PyTorch 版本: 2.5.1
----------------------------------------
CUDA 是否可用: True
----------------------------------------
偵測到的 GPU 數量: 1
目前使用的 GPU ID: 0
目前 GPU 名稱: NVIDIA GeForce RTX 3060
PyTorch 編譯所用的 CUDA 版本: 11.8
----------------------------------------
執行一個簡單的張量運算來驗證 CUDA 核心...
原始 CPU 張量:
 tensor([[-0.3865, -0.3157,  2.1781, -0.0171],
        [-0.0622,  1.1302, -0.1418, -0.1981],
        [ 1.2061, -0.6070, -0.3308,  1.1862]])
移動到 GPU 後的張量:
 tensor([[-0.3865, -0.3157,  2.1781, -0.0171],
        [-0.0622,  1.1302, -0.1418, -0.1981],
        [ 1.2061, -0.6070, -0.3308,  1.1862]], device='cuda:0')
張量所在的設備: cuda:0

在 GPU 上運算的結果:
 tensor([[ 0.2269,  0.3686,  5.3562,  0.9658],
        [ 0.8757,  3.2604,  0.7164,  0.6038],
        [ 3.4122, -0.2141,  0.3384,  3.3724]], device='cuda:0')

將結果移回 CPU:
 tensor([[ 0.2269,  0.3686,  5.3562,  0.9658],
        [ 0.8757,  3.2604,  0.7164,  0.6038],
        [ 3.4122, -0.2141,  0.3384,  3.3724]])
運算結果所在的設備: cpu

測試成功！PyTorch 已正確在您的 GPU 上執行運算。
